command: ["python", "app.py"]

env:
  - name: "DATABRICKS_HOST"
    value: "https://dbc-ad3c1cf3-8c4e.cloud.databricks.com"
  - name: "DATABRICKS_WAREHOUSE_ID"
    value: "dbe4e9c258a53bdf"
  - name: "DATABRICKS_CATALOG"
    value: "dataknobs_predictive_maintenance_and_asset_management"
  - name: "DATABRICKS_SCHEMA"
    value: "datasets"
  - name: "GENIE_SPACE_ID"
    value: "01f1147bd659157cb3fb6a0a74e58e23"
  - name: "BEDROCK_REGION"
    value: "us-east-1"
  - name: "USE_MOCK_AI"
    value: "false"
